version: "3.8"

services:
  app:
    extends:
      file: ./backend/docker-compose.yml
      service: app
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: stream_voice
      POSTGRES_PASSWORD: stream_voice12#$

    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  pg_data:
